; This file was auto-generated by drush make
core = 6.x

api = 2
projects[] = "drupal"
; Modules
projects[admin_menu][subdir] = "contrib"

projects[ctools][subdir] = "contrib"

projects[cck][subdir] = "contrib"

projects[context][subdir] = "contrib"

projects[features][subdir] = "contrib"

projects[filefield][subdir] = "contrib"

projects[fserver][subdir] = "contrib"

projects[nodereference_url][subdir] = "contrib"

projects[strongarm][subdir] = "contrib"

projects[views][subdir] = "contrib"

; Themes
projects[] = "tao"
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[singular][download][type] = ""
projects[singular][download][url] = ""
projects[singular][location] = ""
projects[singular][type] = "theme"

